project:
  type: website
  output-dir: docs
  resources:
    - ads.txt 

website:
  title: "quantdev.blog"
  site-url: "http://quantdev.blog"
  description: "quantdev.blog"
  navbar:
    right:
      - about.qmd
      - text: "Sell-side Quant"
        href: sell_side_quant_critical_path.qmd        
      - text: "C++ Roadmap"
        href: roadmap.qmd
      - icon: patreon
        href: https://patreon.com/u59411143?utm_medium=unknown&utm_source=join_link&utm_campaign=creatorshare_creator&utm_content=copyLink
        text: "Become a patreon"
      - icon: github
        href: https://github.com/quasar-chunawala
      - icon: linkedin
        href: http://linkedin.com/in/quasar-chunawala
      - icon: rss
        href: index.xml
  comments:
    giscus:
      repo: quasar-chunawala/quantdev

format:
  html:
    code-tools: false
    code-annotations: below
    code-line-numbers: true
    code-overflow: scroll
    highlight-style: arrow
    # highlight-style: custom-dark
    theme: flatly
    css: styles.css
    grid:
        sidebar-width: 225px
        body-width: 1100px
        margin-width: 240px
        gutter-width: 1.5rem
 
    mainfont: "Open Sans"
    monofont: "JetBrains Mono"
    monofontsize: 14px
    
    fontsize: 18px
    include-in-header:
      text: |
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;800&display=swap');
          @import url('https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap');
          @import url('https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700&display=swap');
          @import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap');
          @import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Source+Code+Pro:ital,wght@0,200..900;1,200..900&display=swap');
          @import url('https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap');
          @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap')
        </style>
adsense:
  publisher-id: ca-pub-9993009899870547

filters:
- adsense


