project:
  type: website
  output-dir: docs
  resources:
    - ads.txt 

website:
  title: "quantdev.blog"
  site-url: "https://quantdev.blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: rss
        href: index.xml
format:
  html:
    code-tools: true
    code-block-border-left: true
    code-annotations: below
    highlight-style: pygments
    theme: flatly
    css: styles.css
    grid:
        sidebar-width: 200px
        body-width: 1100px
        margin-width: 200px
        gutter-width: 1.5rem
 
    mainfont: "Open Sans"
    monofont: "Source Code Pro"
    fontsize: 16px
    include-in-header:
      text: |
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;800&display=swap');
          @import url('https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap');
          @import url('https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700&display=swap');
          @import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap');
          @import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Source+Code+Pro:ital,wght@0,200..900;1,200..900&display=swap');
          @import url('https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap');
        </style>
adsense:
  publisher-id: ca-pub-9993009899870547

filters:
- adsense


